INIT_FILE = 'init.jiig'
TASKS_FILE = 'tasks.jiig'
TEMPLATE_EXTENSION = '.template'
TEMPLATE_EXTENSION_EXE = '.template_exe'
TEMPLATE_EXTENSION_DOT = '.template_dot'
ALL_TEMPLATE_EXTENSIONS = [
    TEMPLATE_EXTENSION,
    TEMPLATE_EXTENSION_EXE,
    TEMPLATE_EXTENSION_DOT,
]
TOOL_TEMPLATE_FOLDER = 'tool-template'
TEMPLATES_FOLDER = 'templates'
TASK_TEMPLATE = 'task.py.template'
TEMPLATE_FOLDER_SYMBOL_PATTERN = r'\(=(\w+)=\)'

# Command line parsing constants.
CLI_DEST_NAME_PREFIX = 'TASK'
CLI_DEST_NAME_SEPARATOR = '.'
CLI_DEST_NAME_PREAMBLE = CLI_DEST_NAME_PREFIX + CLI_DEST_NAME_SEPARATOR
CLI_METAVAR_SUFFIX = 'SUB_TASK'
CLI_METAVAR_SEPARATOR = '_'

DEBUG = False
VERBOSE = False
DRY_RUN = False
